#!/bin/bash
# ============================================================
#  CexiStore Bot — One-Click Installer
#  Supports: VPS (Ubuntu/Debian), Pterodactyl Panel, Termux
#  Just run: bash install.sh (reads config from .env)
# ============================================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

print_banner() {
  echo -e "${CYAN}"
  echo "╔═══════════════════════════════════════════╗"
  echo "║       🤖 CexiStore Bot Installer          ║"
  echo "║       Version 4.7 — Auto Setup            ║"
  echo "╚═══════════════════════════════════════════╝"
  echo -e "${NC}"
}

log_info()  { echo -e "${GREEN}[✓]${NC} $1"; }
log_warn()  { echo -e "${YELLOW}[!]${NC} $1"; }
log_error() { echo -e "${RED}[✗]${NC} $1"; }
log_step()  { echo -e "${CYAN}[→]${NC} ${BOLD}$1${NC}"; }

# ─── Bot Configuration ────────────────────────────────────────
BOT_TOKEN="8366953140:AAGaHIYpL0kd7kgwQVOpMBZckQeI-XQVsec"
SUPA_URL="https://yzjsmtxhpdlsniqpcuoa.supabase.co"
SUPA_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6anNtdHhocGRsc25pcXBjdW9hIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NDkzOTY4NCwiZXhwIjoyMDgwNTE1Njg0fQ.ooTln0pbYcRu6cta7TFM9qr7hamkT2pqc9JK1_WKtvQ"
OWNER_ID="8402309532"
STORE_NAME="CexiStore Ultimate Pro"
CURRENCY="RM"

# ─── Detect Environment ──────────────────────────────────────
detect_environment() {
  if [ -d "/home/container" ] && [ -n "$STARTUP" ]; then
    ENV_TYPE="pterodactyl"
    INSTALL_DIR="/home/container"
  elif [ -n "$TERMUX_VERSION" ] || [ -d "$PREFIX/bin" ]; then
    ENV_TYPE="termux"
    INSTALL_DIR="$HOME/cexistore-bot"
  else
    ENV_TYPE="vps"
    INSTALL_DIR="$HOME/cexistore-bot"
  fi

  log_info "Environment: ${BOLD}${ENV_TYPE}${NC}"
  log_info "Install dir: ${BOLD}${INSTALL_DIR}${NC}"
}

# ─── Install Node.js ──────────────────────────────────────────
install_node() {
  if command -v node &> /dev/null; then
    NODE_VER=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
    if [ "$NODE_VER" -ge 18 ]; then
      log_info "Node.js $(node -v) ✓"
      return
    else
      log_warn "Node.js v$(node -v) too old, need >= 18"
    fi
  fi

  log_step "Installing Node.js..."

  case $ENV_TYPE in
    termux)
      pkg update -y && pkg install -y nodejs git
      ;;
    pterodactyl)
      if ! command -v node &> /dev/null; then
        log_error "Node.js not found! Use a Node.js egg in Pterodactyl."
        exit 1
      fi
      ;;
    vps)
      if command -v apt-get &> /dev/null; then
        curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
        sudo apt-get install -y nodejs git
      elif command -v yum &> /dev/null; then
        curl -fsSL https://rpm.nodesource.com/setup_20.x | sudo bash -
        sudo yum install -y nodejs git
      elif command -v pacman &> /dev/null; then
        sudo pacman -Sy --noconfirm nodejs npm git
      else
        log_error "Unsupported package manager. Install Node.js 18+ manually."
        exit 1
      fi
      ;;
  esac

  log_info "Node.js $(node -v) installed ✓"
}

# ─── Setup Project ────────────────────────────────────────────
setup_project() {
  log_step "Setting up project..."

  if [ "$ENV_TYPE" = "pterodactyl" ]; then
    if [ ! -f "$INSTALL_DIR/package.json" ]; then
      log_error "Upload bot files to Pterodactyl server first!"
      exit 1
    fi
  else
    SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
    if [ -f "$SCRIPT_DIR/package.json" ]; then
      INSTALL_DIR="$SCRIPT_DIR"
    elif [ -d "$INSTALL_DIR" ] && [ -f "$INSTALL_DIR/package.json" ]; then
      true
    else
      log_error "Run this script from the project directory!"
      exit 1
    fi
  fi

  cd "$INSTALL_DIR"
  log_info "Working in: $(pwd)"
}

# ─── Install Dependencies ────────────────────────────────────
install_deps() {
  log_step "Installing dependencies..."
  npm install --production
  log_info "Dependencies installed ✓"
}

# ─── Auto Create .env ─────────────────────────────────────────
configure_env() {
  log_step "Creating .env file..."

  cat > .env << EOF
# CexiStore Bot Configuration (auto-generated by install.sh)
TELEGRAM_BOT_TOKEN=$BOT_TOKEN

SUPABASE_URL=$SUPA_URL
SUPABASE_KEY=$SUPA_KEY

OWNER_ID=$OWNER_ID

STORE_NAME=$STORE_NAME
STORE_CURRENCY=$CURRENCY
SESSION_TIMEOUT=14400000
EOF

  chmod 600 .env
  log_info ".env created ✓"
}

# ─── Create Directories ──────────────────────────────────────
setup_dirs() {
  mkdir -p data/backup data/images data/qr
  log_info "Data directories created ✓"
}

# ─── Process Manager ─────────────────────────────────────────
setup_process_manager() {
  log_step "Setting up process manager..."

  case $ENV_TYPE in
    pterodactyl)
      log_info "Pterodactyl manages the process"
      log_info "Startup command: node index.js"
      ;;
    termux)
      cat > start.sh << 'STARTEOF'
#!/bin/bash
cd "$(dirname "$0")"
echo "🤖 Starting CexiStore Bot..."
node index.js
STARTEOF
      chmod +x start.sh

      cat > stop.sh << 'STOPEOF'
#!/bin/bash
pkill -f "node index.js" 2>/dev/null && echo "Bot stopped" || echo "Bot not running"
STOPEOF
      chmod +x stop.sh

      log_info "Created start.sh & stop.sh"
      ;;
    vps)
      if ! command -v pm2 &> /dev/null; then
        sudo npm install -g pm2
      fi

      cat > ecosystem.config.js << 'PM2EOF'
module.exports = {
  apps: [{
    name: 'cexistore-bot',
    script: 'index.js',
    instances: 1,
    autorestart: true,
    watch: false,
    max_memory_restart: '256M',
    env: { NODE_ENV: 'production' }
  }]
};
PM2EOF

      log_info "PM2 configured ✓"
      ;;
  esac
}

# ─── Finish & Auto Start ─────────────────────────────────────
finish() {
  echo ""
  echo -e "${GREEN}╔═══════════════════════════════════════════╗${NC}"
  echo -e "${GREEN}║       ✅ Installation Complete!            ║${NC}"
  echo -e "${GREEN}╚═══════════════════════════════════════════╝${NC}"
  echo ""

  case $ENV_TYPE in
    pterodactyl)
      echo -e "${BOLD}Start:${NC} Click ${GREEN}Start${NC} in Pterodactyl panel"
      ;;
    termux)
      echo -e "${BOLD}Start:${NC}  ${CYAN}./start.sh${NC}"
      echo -e "${BOLD}Stop:${NC}   ${CYAN}./stop.sh${NC}"
      ;;
    vps)
      echo -e "${BOLD}Start:${NC}     ${CYAN}pm2 start ecosystem.config.js${NC}"
      echo -e "${BOLD}Stop:${NC}      ${CYAN}pm2 stop cexistore-bot${NC}"
      echo -e "${BOLD}Logs:${NC}      ${CYAN}pm2 logs cexistore-bot${NC}"
      echo -e "${BOLD}Auto-boot:${NC} ${CYAN}pm2 startup && pm2 save${NC}"
      ;;
  esac

  echo ""
  echo -e "${YELLOW}📋 Bot Commands:${NC}"
  echo "  /start    — Main menu"
  echo "  /admin    — Admin panel"
  echo "  /additem  — Add auto-delivery item"
  echo "  /additems — Bulk import items"
  echo "  /ping     — Health check"
  echo ""

  # Auto-start the bot
  log_step "Starting bot..."
  case $ENV_TYPE in
    pterodactyl|termux)
      node index.js
      ;;
    vps)
      pm2 start ecosystem.config.js
      pm2 save
      log_info "Bot running! Use 'pm2 logs cexistore-bot' to view logs."
      ;;
  esac
}

# ─── Main ─────────────────────────────────────────────────────
main() {
  print_banner
  detect_environment
  install_node
  setup_project
  install_deps
  configure_env
  setup_dirs
  setup_process_manager
  finish
}

main "$@"
